# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tagger.ui'
##
## Created by: Qt User Interface Compiler version 6.0.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from my_label import MediaLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(895, 605)
        self.previous = QAction(MainWindow)
        self.previous.setObjectName(u"previous")
        icon = QIcon()
        icon.addFile(u"icons/previous.png", QSize(), QIcon.Normal, QIcon.On)
        self.previous.setIcon(icon)
        self.next = QAction(MainWindow)
        self.next.setObjectName(u"next")
        icon1 = QIcon()
        icon1.addFile(u"icons/next.png", QSize(), QIcon.Normal, QIcon.On)
        self.next.setIcon(icon1)
        self.actionRotate_left = QAction(MainWindow)
        self.actionRotate_left.setObjectName(u"actionRotate_left")
        icon2 = QIcon()
        icon2.addFile(u"icons/rotate_left.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionRotate_left.setIcon(icon2)
        self.actionRotate_Right = QAction(MainWindow)
        self.actionRotate_Right.setObjectName(u"actionRotate_Right")
        icon3 = QIcon()
        icon3.addFile(u"icons/rotate_right.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionRotate_Right.setIcon(icon3)
        self.actionPlay = QAction(MainWindow)
        self.actionPlay.setObjectName(u"actionPlay")
        icon4 = QIcon()
        icon4.addFile(u"icons/play_tagger.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionPlay.setIcon(icon4)
        self.actionCrop = QAction(MainWindow)
        self.actionCrop.setObjectName(u"actionCrop")
        self.actionThumbnail_Bar = QAction(MainWindow)
        self.actionThumbnail_Bar.setObjectName(u"actionThumbnail_Bar")
        self.actionReload = QAction(MainWindow)
        self.actionReload.setObjectName(u"actionReload")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionMirror = QAction(MainWindow)
        self.actionMirror.setObjectName(u"actionMirror")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        icon5 = QIcon()
        icon5.addFile(u"icons/delete.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionDelete.setIcon(icon5)
        self.actionActual_Size = QAction(MainWindow)
        self.actionActual_Size.setObjectName(u"actionActual_Size")
        self.actionBrowser = QAction(MainWindow)
        self.actionBrowser.setObjectName(u"actionBrowser")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(629, 0, 260, 381))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(260, 0))
        self.frame.setMaximumSize(QSize(260, 16777215))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.widget = QWidget(self.frame)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 10, 251, 238))
        self.formLayout = QFormLayout(self.widget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.checkBox = QCheckBox(self.widget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setMinimumSize(QSize(120, 0))
        self.checkBox.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.checkBox)

        self.checkBox_7 = QCheckBox(self.widget)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.checkBox_7)

        self.checkBox_2 = QCheckBox(self.widget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setMinimumSize(QSize(120, 0))
        self.checkBox_2.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.checkBox_2)

        self.checkBox_3 = QCheckBox(self.widget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setMinimumSize(QSize(120, 0))
        self.checkBox_3.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.checkBox_3)

        self.checkBox_10 = QCheckBox(self.widget)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setMinimumSize(QSize(120, 0))
        self.checkBox_10.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.checkBox_10)

        self.checkBox_4 = QCheckBox(self.widget)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.checkBox_4)

        self.checkBox_5 = QCheckBox(self.widget)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.checkBox_5)

        self.checkBox_6 = QCheckBox(self.widget)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.checkBox_6)

        self.checkBox_8 = QCheckBox(self.widget)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setMinimumSize(QSize(120, 0))
        self.checkBox_8.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.checkBox_8)

        self.checkBox_9 = QCheckBox(self.widget)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.checkBox_9)

        self.pushButton = QPushButton(self.widget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setMaximumSize(QSize(120, 16777215))

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.pushButton)

        self.widget1 = QWidget(self.frame)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(10, 319, 240, 52))
        self.gridLayout = QGridLayout(self.widget1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.widget1)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)

        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.save_button = QPushButton(self.widget1)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setVisible(True)

        self.gridLayout.addWidget(self.save_button, 1, 0, 1, 1)

        self.no_save_button = QPushButton(self.widget1)
        self.no_save_button.setObjectName(u"no_save_button")
        self.no_save_button.setVisible(True)

        self.gridLayout.addWidget(self.no_save_button, 1, 1, 1, 1)

        self.media = MediaLabel(self.centralwidget)
        self.media.setObjectName(u"media")
        self.media.setGeometry(QRect(0, 0, 631, 541))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.media.sizePolicy().hasHeightForWidth())
        self.media.setSizePolicy(sizePolicy1)
        self.media.setCursor(QCursor(Qt.ArrowCursor))
        self.media.setMouseTracking(False)
        self.media.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.media.setAutoFillBackground(False)
        self.media.setStyleSheet(u"background: #000;")
        self.media.setScaledContents(False)
        self.media.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 895, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.toolBar.addAction(self.actionBrowser)
        self.toolBar.addAction(self.actionRotate_left)
        self.toolBar.addAction(self.actionRotate_Right)
        self.toolBar.addAction(self.actionCrop)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.previous)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.next)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionMirror)
        self.toolBar.addAction(self.actionActual_Size)

        self.retranslateUi(MainWindow)
        self.no_save_button.clicked.connect(self.actionReload.trigger)
        self.no_save_button.clicked.connect(self.label.hide)
        self.no_save_button.clicked.connect(self.no_save_button.hide)
        self.no_save_button.clicked.connect(self.save_button.hide)
        self.save_button.clicked.connect(self.no_save_button.hide)
        self.save_button.clicked.connect(self.save_button.hide)
        self.save_button.clicked.connect(self.label.hide)
        self.actionMirror.triggered.connect(self.save_button.show)
        self.actionMirror.triggered.connect(self.no_save_button.show)
        self.actionMirror.triggered.connect(self.label.show)
        self.actionRotate_Right.triggered.connect(self.label.show)
        self.actionRotate_Right.triggered.connect(self.no_save_button.show)
        self.actionRotate_Right.triggered.connect(self.save_button.show)
        self.actionRotate_left.triggered.connect(self.label.show)
        self.actionRotate_left.triggered.connect(self.save_button.show)
        self.actionRotate_left.triggered.connect(self.no_save_button.show)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.previous.setText(QCoreApplication.translate("MainWindow", u"<<", None))
#if QT_CONFIG(tooltip)
        self.previous.setToolTip(QCoreApplication.translate("MainWindow", u"View the previous slide.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.previous.setShortcut(QCoreApplication.translate("MainWindow", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.next.setText(QCoreApplication.translate("MainWindow", u">>", None))
#if QT_CONFIG(tooltip)
        self.next.setToolTip(QCoreApplication.translate("MainWindow", u"View the next slide.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.next.setShortcut(QCoreApplication.translate("MainWindow", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.actionRotate_left.setText(QCoreApplication.translate("MainWindow", u"Rotate left", None))
        self.actionRotate_Right.setText(QCoreApplication.translate("MainWindow", u"Rotate Right", None))
        self.actionPlay.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.actionCrop.setText(QCoreApplication.translate("MainWindow", u"Crop", None))
        self.actionThumbnail_Bar.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Bar", None))
        self.actionReload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionMirror.setText(QCoreApplication.translate("MainWindow", u"Mirror", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.actionActual_Size.setText(QCoreApplication.translate("MainWindow", u"Actual Size", None))
        self.actionBrowser.setText(QCoreApplication.translate("MainWindow", u"Browser", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the image", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Ass", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Close-up", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Breasts", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Pussy", None))
        self.checkBox_10.setText(QCoreApplication.translate("MainWindow", u"Ass(exposed)", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Fully Clothed", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Half-Naked", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Naked", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"Smiling", None))
        self.checkBox_9.setText(QCoreApplication.translate("MainWindow", u"Glaring", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Save Tags", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Current image modified, save it?", None))
        self.save_button.setText(QCoreApplication.translate("MainWindow", u"Yes (Save)", None))
        self.no_save_button.setText(QCoreApplication.translate("MainWindow", u"No (Reload)", None))
        self.media.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOptions.setTitle(QCoreApplication.translate("MainWindow", u"Options", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi
